# Generated by Django 4.2.7 on 2023-11-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(default=False, verbose_name='Разговор состоялся')),
                ('comment', models.CharField(max_length=250, null=True, verbose_name='Комментарий сотрудника')),
                ('date_call', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время звонка')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('otch', models.CharField(max_length=20, null=True, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('ref', models.TextField(verbose_name='Кто привел кандидата')),
                ('auto', models.BooleanField(default=False, verbose_name='Наличие автомобиля')),
                ('resume', models.FileField(upload_to='', verbose_name='Файл резюме')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_change', models.IntegerField(choices=[(1, 'Новый'), (2, 'Созвон'), (3, '3-й недозвон'), (4, 'Резюме'), (5, 'Стажировка'), (6, 'Оформление'), (7, 'Отказ'), (8, 'Кадровый резерв')], default=1, verbose_name='Текущий статус')),
                ('status_change_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения статуса')),
                ('appointment_date', models.DateField(verbose_name='Назначенная дата')),
                ('event', models.BooleanField(default=False, verbose_name='Состоялось событие')),
                ('comment', models.TextField(verbose_name='Коментарий')),
            ],
        ),
        migrations.CreateModel(
            name='CPHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, verbose_name='Статус')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Зафиксированное время')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False, verbose_name='Просмотрено')),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_req', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsibilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_resp', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_vacancy', models.IntegerField(choices=[(1, 'Открыта'), (2, 'Закрыта'), (3, 'Приостановлена')], default=1, verbose_name='Статус вакансии')),
                ('date_cust', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления вакансии')),
                ('name_vacancy', models.CharField(max_length=250, verbose_name='Название вакансии')),
                ('description_vacancy', models.TextField(verbose_name='Описание вакансии')),
                ('region', models.CharField(max_length=250, verbose_name='Место работы')),
                ('salary', models.IntegerField(default=0, verbose_name='Зарплата')),
                ('motivation', models.IntegerField(default=0, verbose_name='Дополнительная мотивация (Сумма)')),
                ('auto', models.BooleanField(default=False, verbose_name='Наличие автомобиля')),
                ('gsm', models.IntegerField(default=0, verbose_name='Расходы на топливо')),
                ('substitute', models.BooleanField(default=False, verbose_name='Подменный сотрудник')),
                ('type_job', models.BooleanField(default=False, verbose_name='Удаленная работа')),
                ('intern', models.IntegerField(choices=[(1, 'Наставник'), (2, 'Мерчендайзер'), (3, 'Супервайзер'), (4, 'Удаленно')], default=1, verbose_name='Вид стажировки')),
                ('schedule', models.CharField(max_length=30, verbose_name='График работы')),
                ('count_hours', models.IntegerField(verbose_name='Среднее количество часов в день')),
                ('count_tt', models.IntegerField(verbose_name='Среднее количество ТТ в день')),
                ('cause', models.CharField(max_length=500, verbose_name='Причина открытия вакансии')),
            ],
        ),
    ]
